---
fixtures:
  repositories:
    auditd: "git://github.com/simp/pupmod-simp-auditd"
    common: "git://github.com/simp/pupmod-simp-common"
    simplib: "git://github.com/simp/pupmod-simp-simplib"
    simpcat: "git://github.com/simp/pupmod-simp-concat"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
  symlinks:
    upstart: "#{source_dir}"
